### ISSUE TITLE
Convert gatsby-i18n-create-page to full open source project

### ISSUE THREAD

**Issue by JohnAlbin** [AmazeeLabs/gatsby-starter-amazee#140]
This might be useful as a independent plugin.

HOWTO: https://itnext.io/step-by-step-building-and-publishing-an-npm-typescript-package-44fe7164964c

**Comment by pmelab** [comment]
While prototyping #23 , I discovered that this will require some changes. So it would make sense to block this issue until #23 is done.

**Comment by pmelab** [comment]
Apparently there will be an official [i18n extension](https://www.gatsbyjs.org/blog/2020-06-23-Reconfiguring-Gatsby-Days/#i18n-theme). Maybe we should participate there.

**Comment by dan2k3k4** [comment]
That's currently: https://github.com/LekoArts/gatsby-theme-i18n
