### ISSUE TITLE
Github Pages build is styled

### ISSUE THREAD

**Issue by dan2k3k4** [AmazeeLabs/gatsby-starter-amazee#143]
**Describe the bug**
Currently the Github Pages build is not styled due to a recent bug.

**To Reproduce**

1. Go to https://amazeelabs.github.io/gatsby-starter-amazee/
2. It is unstyled, it should be styled.

**Expected behavior**
We should see a page styled with our chosen branding.

**Additional context**
It seems that the recent commits broke the Travis build and may have also caused the issue with the Github Pages build.

**Comment by dan2k3k4** [comment]
We could perhaps add a visual diff test 🤔

**Comment by dan2k3k4** [comment]
Closing as the Github Page is styled again

**Comment by JohnAlbin** [comment]
Yep. It's item 6 on the list of https://github.com/AmazeeLabs/gatsby-starter-amazee/issues/144
