### ISSUE TITLE
Remove Apollo and suggest full-stack project structure

### ISSUE THREAD

**Issue by pmelab** [AmazeeLabs/gatsby-starter-amazee#164]
Adding Apollo to the starter kit was a little premature. Only a fraction of the potential projects will actually use it and for all others, it's just unnecessary complexity and confusion. The data-mocking part that Apollo currently brings can be solved with more generic approaches (see #163 ).

A brief discussion with @Leksat concluded in an agreement that we definitely want backend solutions (Drupal, Apollo ...) to be part of the same repository to not drown in pull request madness, but separate them at the root level (as we already have done it with other projects before).

```
./gatsby -> gatsby starter
./apollo -> Apollo server
./drupal -> Drupal :)
./e2e -> E2E integration tests
./shared -> possibly shared code / type definitions between gatsby, apollo and cypress
```

This way we could also make sure to only run relevant test suites based the directories where changes happened. 

@dan2k3k4 : The main `TODO` here is to find out if we can make dependabot update all different directories for us.

**Comment by dan2k3k4** [comment]
`dependabot` should be able to accept the multiple different files to check and update, at least pre-Github version worked like that. I assume the newer v2 Github version still supports this, as it's especially handy for projects with mono-repos.

**Comment by pmelab** [comment]
Following this thread leads to the thought if *every* subsystem should get its own root. We currently have 5 potential runtimes.

* Apollo
* Gatsby
* Storybook
* Cypress
* Drupal

4 of them are maintained in the same package, essentially because all are node-based and thus we can. But that doesn't feel like a good reason. In reality, all of them represent different processes, and sometimes even collide (jest/cypress typing conflict). Depending on the project, the number of subsystems also varies (No backend, Drupal or Apollo, Drupal *and* Apollo, multiple frontends ...). It feels right to separate these since they are loosely coupled anyway and reduce the complexity that is aggregated in just the starter kit. But I'm not sure if we trade it for more overhead.


@JohnAlbin already suggested separating the "Design System" from the "Application". I think the same concerns regarding single/multiple repositories apply, although I feel storybook is a little tighter coupled to Gatsby than Gatsby to Apollo.

Some questions that come into my mind:

* Would Storybook maintain Gatsby queries? (leaning towards "no")
* Would Storybook maintain Apollo queries? (leaning towards "yes")
* Would Storybook maintain other react hooks/utilities? (leaning towards "yes")
