### ISSUE TITLE
Add generic Meta component to handle metatags

### ISSUE THREAD

**Issue by dan2k3k4** [AmazeeLabs/gatsby-starter-amazee#45]
We have already added `react-helmet` to the `package.json` file.

We'll need to add the dev dependency: `@types/react-helmet` for our typescript support.

Then we'll need to create a `<Head>` component (or `<SEO>`) which can allow us to define the page title, description, and image as a starting point.

This may help: https://www.gatsbyjs.org/docs/add-seo-component/

**Comment by JohnAlbin** [comment]
> We'll need to add the dev dependency: @types/react-helmet for our typescript support.

BTW, this is why you don't just "throw in a dependency into this PR because it's one line and we'll need it later". :) Since it wasn't actually used in that PR, there was no way to test that it worked. And since there's no typescript support for helmet yet, it doesn't actually work.

**Comment by dan2k3k4** [comment]
We may want to switch to `react-helmet-async` and there's a Gatsby plugin that exists:
https://www.gatsbyjs.org/packages/gatsby-plugin-react-helmet-async/

Also I wondered whether the `Head` component should also wrap the calls to `seo.title` with the translation `t()` function such that it ends up like:
`<Helmet title={t(seo.title)}>`

As the first call on say the homepage `/` uses the default title defined in the `gatsby-config.ts` file, which is not translated.

**Comment by JohnAlbin** [comment]
+1 on using `react-helmet-async` instead of `react-helmet`

**Comment by JohnAlbin** [comment]
Thanks for adding a comment about this. I'd forgotten we had discussed this point. Yes, having a simplified prop interface on a component is going to be easier than trying to remember how Open Graph, Twitter cards, etc. interact with each other.

**Comment by JohnAlbin** [comment]
Since we're getting a `Title` component in #90, let's call this `Meta`.
