### ISSUE TITLE
Fix languageswitcher on gh-pages build

### ISSUE THREAD

**Issue by JohnAlbin** [AmazeeLabs/gatsby-starter-amazee#78]
Probably related to our navigate override of Gatsby's navigate function. 

The sub-directory support is via this feature: https://www.gatsbyjs.org/docs/path-prefix/

**Comment by dan2k3k4** [comment]
Also FYI, the path prefix is only used on the [Github pages workflow](/AmazeeLabs/gatsby-starter-amazee/blob/master/.github/workflows/deploy-gh-pages.yml#L33).

If you need to debug this locally, you would probably need to run `yarn --cwd /build serve` or something similar after building with Gatsby's prefix paths. Or to move the build into a sub-folder and serve the root directory then navigate to the sub-folder to replicate Github Pages locally.

The only documentation I found about `--cwd` flag is in `yarn help`

`--cwd <cwd>                         working directory to use`
